#!/bin/env sh

NAME=$(cat package.json | jq -r '.name')
VERSION=$(cat package.json | jq -r '.version')
SCRIPT_PATH=$(dirname $(realpath $0))
podman build -t $NAME:$VERSION -v ${SCRIPT_PATH}/.cache:/app/.cache:Z .